Rack-interface example
Sophiliya/rack-app pull request #1
Opened 2020-11-16 16:00 UTC by Sophiliya

2020-11-16 18:26 UTC, BubuntuClu requested changes

2020-11-16 18:26 UTC, BubuntuClu commented on time_formatter.rb
> +    unknown_formats = @formats.select { |format| !FORMATS.keys.include?(format) }
у тебя два раза делается прогон по одному массиву, ты можешь за один раз получить массив валидных и невалидных ключей

2020-11-16 18:26 UTC, BubuntuClu commented on app.rb
> +    response = body(
имя метода `body` не говорящее, вообще даже не похоже что это метод

2020-11-16 18:26 UTC, BubuntuClu commented on app.rb
> +    [ response[:status], headers, response[:body] ]
для ответа используй Rack::Response класс

2020-11-16 18:26 UTC, BubuntuClu commented on app.rb
> +    result(params.last.split('%2C'))
результат чего? так же как и body не дает понятие о том что вернет метод и про что он

2020-11-16 18:26 UTC, BubuntuClu commented on time_formatter.rb
> +    unknown_formats = @formats.select { |format| !FORMATS.keys.include?(format) }
можно сделать метод `call`, который соберет все данные, метод `success?` который ответит тебе какой результат проверки данных и два метода `unknown_formats/time_string` которые будут возвращать то или иное значение

2020-11-16 18:26 UTC, BubuntuClu commented on time_formatter.rb
> +  FORMATS = {
это хорошо

2020-11-16 18:26 UTC, BubuntuClu commented on app.rb
> +    return { status: 405, body: ['Method Not Allowed'] } if method != 'GET'
на мой взгляд лучше сделать `make_response` метод и в него передавать текст и статус

2020-11-16 18:26 UTC, BubuntuClu commented on app.rb
> +    response = body(
тут симпатичней выглядит что-то типа
```
    req = Rack::Request.new(env)

    case req.path_info
    when /time/
      time_request_handler (req)
    ....
    else
      make_response(404, "Not found")
    end
```

разбить на логические сегменты-методы

2020-11-23 18:34 UTC, BubuntuClu commented on app.rb
> +    [status, headers, [message]]
с Rack::Response не получилось?

2020-11-23 18:35 UTC, BubuntuClu requested changes

2020-11-23 18:35 UTC, BubuntuClu commented on app.rb
> +    make_response(formatted_time(formats), 200)
если у тебя встретится неизвестный формат, то сообщение будет об ошибке, но статус будет 200, а надо 400. раздели получение правильной строки и сообщения об ошибке

2020-11-23 18:35 UTC, BubuntuClu commented on time_formatter.rb
> +    unknown_formats = @formats.select { |format| !FORMATS.keys.include?(format) }
эту часть не получилось исправить?

2020-11-24 15:53 UTC, Sophiliya commented on app.rb
> +    [status, headers, [message]]
не получилось, возникает ошибка:
`NoMethodError: undefined method `[]=' for nil:NilClass`

2020-11-24 19:00 UTC, BubuntuClu requested changes

2020-11-24 19:00 UTC, BubuntuClu commented on app.rb
> +    [status, headers, [message]]
попробуй передавать message как строку, а не как массив

2020-11-24 19:00 UTC, BubuntuClu commented on time_formatter.rb
> +    @formats = formats
создай тут два дополнительных объекта
`unknown_formats` и `valid_formast`

2020-11-24 19:00 UTC, BubuntuClu commented on time_formatter.rb
> +  def call
в этом методе ты заполняешь два объекта `unknown_formats` и `valid_formats`

2020-11-24 19:00 UTC, BubuntuClu commented on time_formatter.rb
> +  def success?
это все публичные методы

2020-11-24 19:00 UTC, BubuntuClu commented on app.rb
> +    time_result = TimeFormatter.new(formats).call
```
time_result = TimeFormatter.new(formats)
time_result.call

if time_result.success?
   make_response(time_result.time_string..
else
  make_response(time_result.error_message...
end
```

2020-11-24 19:00 UTC, BubuntuClu commented on app.rb
> +    if time_result[:error]
с хэшами не стоит тут играть. у нас же ООП. все через методы и объекты

2020-11-24 19:00 UTC, BubuntuClu commented on time_formatter.rb
> +  def call
что-то типа
```
@formats.each do |format|
      if FORMATS[format]
        @valid_format += (' ' + FORMATS[format])
      else
        @unknown_format << format
      end
```

2020-11-24 19:00 UTC, BubuntuClu commented on time_formatter.rb
> +    @unknown_formats = @formats - FORMATS.keys
почему проверка успеха делает какую-то лоигку? тут только проверка сама нужна

2020-11-24 19:00 UTC, BubuntuClu commented on time_formatter.rb
> +    @unknown_formats.any? ? false : true
```
def success?
   @unknown_formats.blank?
end
```

2020-11-25 07:03 UTC, merged